In [4]:
import numpy as np
from numpy.random import randn

In [2]:
import pandas as pd
from pandas import Series, DataFrame

#### Creating Arrays
##### Creating arrays using a list

In [5]:
a = np.array([1,2,3,4,5,6])

In [6]:
b = np.array([[10,20,30],[40,50,60]])

In [7]:
# Creating arrays via assigment

In [9]:
np.random.seed(25)
c = 36*np.random.randn(6) # randn function generaly pick random values from positive values and negative values

In [10]:
c

array([  8.21783123,  36.96805091, -30.22505456, -21.28253464,
       -34.44797868,  -8.003725  ])

In [12]:
d = np.arange(1,35)

In [13]:
a*10

array([10, 20, 30, 40, 50, 60])

In [14]:
c-a

array([  7.21783123,  34.96805091, -33.22505456, -25.28253464,
       -39.44797868, -14.003725  ])

In [16]:
c*a

array([   8.21783123,   73.93610183,  -90.67516369,  -85.13013858,
       -172.2398934 ,  -48.02234998])

## Multiplying matricies and basic liniar algebra 

In [17]:
np.set_printoptions(precision=2) #get no more than 2 decimal points

In [19]:
aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])

In [20]:
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [21]:
bb = np.array ([[0,1,2],[3,4,5],[6,7,8]])

In [22]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])